# Generated by Django 3.2.13 on 2022-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
