# Generated by Django 3.2.13 on 2022-07-19 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Visio', '__first__'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Buildings',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=1500)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.building')),
            ],
            options={
                'verbose_name': 'Floors',
                'verbose_name_plural': 'Floors',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=1000)),
                ('total_sensors', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clients')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='InstalledSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_label', models.CharField(max_length=500)),
                ('min_range', models.IntegerField(blank=True, null=True)),
                ('max_range', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=1000)),
                ('alert_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visio.team')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.floor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visio.sensor')),
            ],
            options={
                'verbose_name': 'Installed Sensors',
                'verbose_name_plural': 'Installed Sensor',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
    ]
