# Generated by Django 3.2.13 on 2022-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_total_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='installedsensor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='installedsensor',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
