# Generated by Django 3.2.13 on 2022-07-19 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=1000)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person_phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
