# Generated by Django 3.2.13 on 2022-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20220720_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
