# Generated by Django 3.2.13 on 2022-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_clients_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
